name: Manual workflow
on:
  workflow_call:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
 
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.2.0'
      - name: npm install
        run: |
           npm install autoprefixer@10.4.5 --save-exact
           npm install
      - run: mkdir -p path     
      - run: echo hello > path/test.txt
      - uses: actions/upload-artifact@main
        with:
          name: build-artifact
          path: path/test.txt
#   lint:
#     name: Lint
#     runs-on: self-hosted
#     steps:
#       - uses: actions/checkout@v3
#       - name: Use Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '18.2.0'
#       - run: |
#            npm install autoprefixer@10.4.5 --save-exact
#            npm run lint        
  Testing:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
       - name: build-artifact
         uses: actions/download-artifact@main
         with:
          name: build-artifact
 
#        - name: Code Linting
#          run: npm run lint
  Image:
    needs: [Testing]
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}      
         aws-region: us-east-1
      - name: Login credentials
        run: |
      - name: make build
        run:
         make build
#       - name: make push
#         run:
#          make push
  Deploy:
    needs: [Image]
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}      
         aws-region: us-east-1
      - name: Login credentials
        run: |
         Cross_Acc_Role=$(aws sts assume-role --role-arn arn:aws:iam::779527285137:role/AWSdevopscerttaskrole --role-session-name AWSCLI-Session --profile default ) 
         export AWS_ACCESS_KEY_ID=$(echo $Cross_Acc_Role | jq -r .Credentials.AccessKeyId) 
         export AWS_SECRET_ACCESS_KEY=$(echo $Cross_Acc_Role | jq -r .Credentials.SecretAccessKey)
         export AWS_SESSION_TOKEN=$(echo $Cross_Acc_Role | jq -r .Credentials.SessionToken)
      
      - name: helm install
        run: |
           aws eks --region us-east-1 update-kubeconfig --name test
           helm install app react/ --values react/values.yaml
      
      
           
